version: '3.8'

services:
  gninx:
    container_name: rumitgram_web
    restart: always  #always restart if container fails
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - uploads_volume:/app/uploads
    ports:
      - "80:80" # this is redirect instruction host_port:container_port.
    depends_on:
      - api # waiting for the Django API to start before starting the NGINX server
  db:
    container_name: rumitgram_db
    image: postgres:14.3-alpine
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  api:
    container_name: rumitgram_api
    build: .
    restart: always
    env_file: .env
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py migrate --no-input && gunicorn CoreRoot.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
      - uploads_volume:/app/uploads
    depends_on:
      - db
volumes:
  uploads_volume:
  postgres_data:

