# Generated by Django 4.0 on 2023-08-02 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_post', '0002_rename_autor_post_author'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table=None,
        ),
    ]
