name: Build, Test and Deploy Rumitgram
on:
  push:
    branches: [ main ]  # workflow will run everet time there is a push on the main branch

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Injecting env vars
      run:
        echo "${{ secrets.TEST_SECRETS }}" >> .env
    - name: Building Docker containers
      run: |
        docker-compose up -d --build
        docker-compose logs
    - name: Running Test
      run: |
        docker-compose exec -T api pytest

  deploy:
    name: Deploying on EC2 via SSH
    if: ${{ github.event_name == 'push' }}
    needs: [build-test]
    runs-on: ubuntu-latest
    steps:
    - name: Deploying Applicationon EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_EC2_IP }}
        username: ${{ secrets.SSH_EC2_USER }}
        #username: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        scripts: |
          cd ~/.scripts
          ./docker-ec2-deploy.sh
