name: Build, Test and Deploy Rumitgram
on:
  push:
    branches: [ main ]  # workflow will run everet time there is a push on the main branch

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Injecting env vars
      run:
        echo "SECRET_KET = test_foo
              DATABASE_NAME=test_coredb
              DATABASE_USER=test_core
              DATABASE_PASSWORD=12345678
              DATABASE_HOST=test_rumitgram_db
              DATABASE_PORT=5432
              POSTGRES_USER=test_core
              POSTGRES_PASSWORD=12345678
              POSTGRES_DB=test_coredb
              ENV=TESTING
              DJANGO_ALLOWED_HOSTS=127.0.0.1,localhost" >> .env
    - name: Building Docker containers
      run: |
        docker-compose up -d --build
    - name: Running Test
      run: |
        docker-compose exec -T api pytest